POST http://localhost:8888/api/auth/signup
Content-Type: application/json

{
    "fullname": "Elvis Vela",
    "username": "Elveal",
    "email": "elvis@outlook.com",
    "password": "hola11"
}

###

POST http://localhost:8888/api/auth/login
Content-Type: application/json

{
    "username": "Elveal",
    "password": "hola11"
}

###

POST http://localhost:8888/api/auth/logout

###

POST http://localhost:8888/api/auth/getMe