POST http://localhost:8888/api/auth/signup
Content-Type: application/json

{
    "fullname": "Anjhelo Vela",
    "username": "LOHAN",
    "email": "anjhelo@outlook.com",
    "password": "hola11"
}

###

POST http://localhost:8888/api/auth/login
Content-Type: application/json

{
    "username": "Elveal",
    "password": "hola11"
}
###

POST http://localhost:8888/api/auth/login
Content-Type: application/json

{
    "username": "Angheluchi",
    "password": "lohan123"
}

###

POST http://localhost:8888/api/auth/logout

###

POST http://localhost:8888/api/auth/getMe

### User Endpoints ###

GET http://localhost:8888/api/user/profile/Elveal

###

POST http://localhost:8888/api/user/follow/677c7899c1061dd4af3606c2

###

GET http://localhost:8888/api/user/suggested

###

POST http://localhost:8888/api/user/update
Content-Type: application/json

{
  "bio": "Hola me llamo LoHan",
  "profileImg": "",
  "currentPassword": "lohan123",
  "newPassword": "hola123",
  "coverImg": "https://static.bandainamcoent.eu/high/dark-souls/dark-souls-3/00-page-setup/ds3_game-thumbnail.jpg"
}
